-- Insert ~50 new vocabulary words in the "Hebrew - English" word_pair format
INSERT INTO public.vocabulary_words (word_pair, english_word, hebrew_translation, category, example_sentence)
VALUES
  ('שלום - hello', 'hello', 'שלום', 'בסיס', 'Hello, how are you? - שלום, מה שלומך?'),
  ('להתראות - goodbye', 'goodbye', 'להתראות', 'בסיס', 'Goodbye! See you tomorrow - להתראות! נתראה מחר'),
  ('בבקשה - please', 'please', 'בבקשה', 'בסיס', 'Please close the door - בבקשה סגור את הדלת'),
  ('תודה - thank you', 'thank you', 'תודה', 'בסיס', 'Thank you very much - תודה רבה'),
  ('כן - yes', 'yes', 'כן', 'בסיס', 'Yes, I agree - כן, אני מסכים'),
  ('לא - no', 'no', 'לא', 'בסיס', 'No, thank you - לא, תודה'),
  ('בוקר - morning', 'morning', 'בוקר', 'זמן', 'Good morning, everyone - בוקר טוב לכולם'),
  ('לילה - night', 'night', 'לילה', 'זמן', 'Good night and sweet dreams - לילה טוב וחלומות פז'),
  ('חבר - friend', 'friend', 'חבר', 'אדם', 'He is my best friend - הוא החבר הכי טוב שלי'),
  ('משפחה - family', 'family', 'משפחה', 'אדם', 'My family is big - המשפחה שלי גדולה'),
  ('עבודה - work', 'work', 'עבודה', 'חיים יומיומיים', 'I go to work at nine - אני הולך לעבודה בתשע'),
  ('בית ספר - school', 'school', 'בית ספר', 'חיים יומיומיים', 'The children are at school - הילדים בבית הספר'),
  ('אוניברסיטה - university', 'university', 'אוניברסיטה', 'חיים יומיומיים', 'She studies at the university - היא לומדת באוניברסיטה'),
  ('ספריה - library', 'library', 'ספריה', 'חיים יומיומיים', 'I read at the library - אני קורא בספריה'),
  ('מסעדה - restaurant', 'restaurant', 'מסעדה', 'אוכל', 'We ate at a new restaurant - אכלנו במסעדה חדשה'),
  ('חנות - store', 'store', 'חנות', 'קניות', 'The store opens at ten - החנות נפתחת בעשר'),
  ('בית חולים - hospital', 'hospital', 'בית חולים', 'בריאות', 'He works at the hospital - הוא עובד בבית החולים'),
  ('רופא - doctor', 'doctor', 'רופא', 'בריאות', 'The doctor is kind - הרופא נחמד'),
  ('מהנדס - engineer', 'engineer', 'מהנדס', 'מקצועות', 'He is a software engineer - הוא מהנדס תוכנה'),
  ('מחשב נייד - laptop', 'laptop', 'מחשב נייד', 'טכנולוגיה', 'I bought a new laptop - קניתי מחשב נייד חדש'),
  ('טלפון - phone', 'phone', 'טלפון', 'טכנולוגיה', 'Where is my phone? - איפה הטלפון שלי?'),
  ('אינטרנט - internet', 'internet', 'אינטרנט', 'טכנולוגיה', 'The internet is slow today - האינטרנט איטי היום'),
  ('אפליקציה - app', 'app', 'אפליקציה', 'טכנולוגיה', 'This app is useful - האפליקציה הזאת שימושית'),
  ('אתר - website', 'website', 'אתר', 'טכנולוגיה', 'I built a new website - בניתי אתר חדש'),
  ('חשבון - account', 'account', 'חשבון', 'אינטרנט', 'Create an account - צור חשבון'),
  ('סיסמה - password', 'password', 'סיסמה', 'אינטרנט', 'Change your password - שנה את הסיסמה שלך'),
  ('התחברות - login', 'login', 'התחברות', 'אינטרנט', 'Login to continue - התחבר כדי להמשיך'),
  ('הרשמה - signup', 'signup', 'הרשמה', 'אינטרנט', 'Signup is free - ההרשמה בחינם'),
  ('הגדרה - setting', 'setting', 'הגדרה', 'אינטרנט', 'Open the settings - פתח את ההגדרות'),
  ('עזרה - help', 'help', 'עזרה', 'בסיס', 'I need help - אני צריך עזרה'),
  ('נסיעה - trip', 'trip', 'נסיעה', 'טיולים', 'The trip was fun - הנסיעה הייתה מהנה'),
  ('מטוס - airplane', 'airplane', 'מטוס', 'טיולים', 'The airplane is landing - המטוס נוחת'),
  ('רכבת - train', 'train', 'רכבת', 'טיולים', 'Take the train to the city - קח את הרכבת לעיר'),
  ('מונית - taxi', 'taxi', 'מונית', 'טיולים', 'We need a taxi - אנחנו צריכים מונית'),
  ('מלון - hotel', 'hotel', 'מלון', 'טיולים', 'The hotel is full - המלון מלא'),
  ('כרטיס - ticket', 'ticket', 'כרטיס', 'טיולים', 'I lost my ticket - איבדתי את הכרטיס'),
  ('מפה - map', 'map', 'מפה', 'טיולים', 'The map is old - המפה ישנה'),
  ('ים - sea', 'sea', 'ים', 'טבע', 'The sea is blue - הים כחול'),
  ('הר - mountain', 'mountain', 'הר', 'טבע', 'The mountain is high - ההר גבוה'),
  ('יער - forest', 'forest', 'יער', 'טבע', 'We walked in the forest - הלכנו ביער'),
  ('גשם - rain', 'rain', 'גשם', 'מזג אוויר', 'It will rain today - היום ירד גשם'),
  ('שמש - sun', 'sun', 'שמש', 'מזג אוויר', 'The sun is bright - השמש זורחת'),
  ('שלג - snow', 'snow', 'שלג', 'מזג אוויר', 'It is snowing - יורד שלג'),
  ('מהיר - fast', 'fast', 'מהיר', 'תארים', 'This car is fast - המכונית הזאת מהירה'),
  ('איטי - slow', 'slow', 'איטי', 'תארים', 'The internet is slow - האינטרנט איטי'),
  ('חכם - smart', 'smart', 'חכם', 'תארים', 'She is very smart - היא מאוד חכמה'),
  ('קל - easy', 'easy', 'קל', 'תארים', 'This exercise is easy - התרגיל הזה קל'),
  ('קשה - hard', 'hard', 'קשה', 'תארים', 'The test was hard - המבחן היה קשה'),
  ('שאלה - question', 'question', 'שאלה', 'בסיס', 'I have a question - יש לי שאלה'),
  ('תשובה - answer', 'answer', 'תשובה', 'בסיס', 'That is the right answer - זו התשובה הנכונה');